apiVersion: v1
kind: Service
metadata:
  name: engage-api
  labels:
    app: engage-api
spec:
  selector:
    app: engage-api
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  type: LoadBalancer
